batch_size: 8
iters: 80000

train_dataset:
  type: LevirCD
  dataset_root: data/train_split
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.2
      max_scale_factor: 2.0
      scale_step_size: 0.01
    - type: RandomPaddingCrop
      crop_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: LevirCD
  dataset_root: data/test
  transforms:
    - type: Normalize
  mode: val

model:
  type: UPerNetCDBaseLine
  backbone:
    type: SwinTransformer_tiny_patch4_window7_224
    pretrained: https://paddleseg.bj.bcebos.com/paddleseg3d/backbone/SwinTransformer_tiny_patch4_window7_224_pretrained/model.pdparams
  backbone_indices: [0, 1, 2, 3]
  channels: 512
  dropout_prob: 0.1
  enable_auxiliary_loss: True
  num_classes: 2

optimizer:
  type: AdamW
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.01

lr_scheduler:
  type: PolynomialDecay
  warmup_iters: 1000
  warmup_start_lr: 0.0
  learning_rate: 0.0001
  end_lr: 0
  power: 1

loss:
  types:
    - type: CrossEntropyLoss
  types:
    - type: CrossEntropyLoss
  coef: [1, 0.4]
